# === ПЕРЕМЕННЫЕ ===
$font = JetBrains Mono Nerd Font
$text_color = rgba(205, 214, 244, 1.0)
$sub_text_color = rgba(166, 173, 200, 1.0)
$bg_image = /home/kayros/.config/hypr/assets/lock.jpg
$user_image = /home/kayros/.config/hypr/assets/face.jpg

general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

# === ФОН (BACKGROUND) ===
background {
    monitor =
    path = $bg_image
    blur_passes = 1           # Размытие (0 - нет, 1, 2, 3 - сильнее)
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# === ПОЛЕ ВВОДА ПАРОЛЯ ===
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(30, 30, 46, 0.5)
    font_color = $text_color
    fade_on_empty = false
    placeholder_text = <span foreground="##a6adc8">Password...</span>
    hide_input = false
    check_color = rgba(137, 180, 250, 0.5)
    fail_color = rgba(243, 139, 168, 0.5)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgba(250, 179, 135, 0.5)
    position = 0, -120
    halign = center
    valign = center
}

# === ЧАСЫ (TIME) ===
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $text_color
    font_size = 120
    font_family = $font ExtraBold
    position = 0, -300
    halign = center
    valign = top
}

# === ДАТА (DATE) ===
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = $sub_text_color
    font_size = 30
    font_family = $font
    position = 0, 200
    halign = center
    valign = center
}

# === АВАТАРКА (USER IMAGE) ===
image {
    monitor =
    path = $user_image
    size = 150
    border_color = $sub_text_color
    border_size = 4
    position = 0, 75
    halign = center
    valign = center
}

# === РАСКЛАДКА КЛАВИАТУРЫ ===
label {
    monitor =
    text = Layout: $LAYOUT
    color = $sub_text_color
    font_size = 14
    font_family = $font
    position = 0, -10
    halign = center
    valign = bottom
}
