#################
### AUTOSTART ###
#################

# === 1. БАЗА СИСТЕМЫ (КРИТИЧЕСКОЕ) ===
# Обновляем переменные среды для Wayland (чтобы работал шаринг экрана и XDG)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Агент аутентификации (всплывающее окно пароля для GUI)
exec-once = systemctl --user start hyprpolkitagent

# === 2. ВИЗУАЛ И БЛОКИРОВКА (LOGIN SEQUENCE) ===
# Сначала демон обоев
exec-once = swww-daemon &

# === 3. ИНТЕРФЕЙС ===
exec-once = waybar &             # Панель
exec-once = dunst &              # Уведомления

# === 4. ТРЕЙ И УТИЛИТЫ ===
exec-once = nm-applet &          # Сеть
exec-once = blueman-applet &     # Bluetooth
exec-once = udiskie &            # Авто-монтирование флешек

# === 5. ФОНОВЫЕ СЛУЖБЫ ===
# Автосоздание группы
exec-once = ~/.config/hypr/scripts/auto_group.sh &
# Буфер обмена (текст и картинки)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Интеграция с виртуалкой (буфер обмена хост-гость)
exec-once = spice-vdagent &

# Демон простоя (чтобы экран гас и блокировался сам)
#exec-once = hypridle &
