# Главный модификатор
$mainMod = SUPER                            
# Путь к скриптам
$scripts = ~/.config/hypr/scripts

# ==================== НАВИГАЦИЯ =======================
# Смена фокуса между слотами
bind = $mainMod, L, layoutmsg, cyclenext
# Поменять местами левый и правый слоты
#bind = $mainMod, Space, layoutmsg, swapwithmaster
bind = $mainMod, Space, exec, ~/.config/hypr/scripts/smart_swap.sh
# Предыдущее приложение в левый слот
bind = $mainMod, J, layoutmsg, cycleprev
# Следующее приложение в левый слот
bind = $mainMod, K, layoutmsg, cyclenext
# Развернуть текущий слот на весь экран (фокусировка)
bind = $mainMod, M, fullscreen, 1
# Закрыть текущее окно
bind = $mainMod, C, exec, $scripts/close_tile.sh
# Выход из системы
bind = $mainMod, Delete, exit               

# =============== ЗАПУСК ПРИЛОЖЕНИЙ ===================
bind = $mainMod, Return, exec, kitty         # Терминал
# Rofi - запуск приложений и список открытых окон
bind = $mainMod, I, exec, rofi -show drun -show-icons
bind = $mainMod, O, exec, rofi -show window -show-icons

# ------ Оверлей (передо всеми) -------
# Btop (Системный монитор)
bind = $mainMod, Q, exec, $scripts/open_overlay_tile.sh "kitty --class btop btop"
# Wi-Fi / Сеть (GUI)
bind = $mainMod, W, exec, $scripts/open_overlay_tile.sh "nm-connection-editor"
# Bluetooth (Blueman)
bind = $mainMod, E, exec, $scripts/open_overlay_tile.sh "blueman-manager"
# Tune / Zvuk (Pavucontrol) - Микшер громкости
bind = $mainMod, R, exec, $scripts/open_overlay_tile.sh "pavucontrol"
# Transmission (Торренты) - НОВОЕ
bind = $mainMod, T, exec, $scripts/open_overlay_tile.sh "transmission-gtk"
# U: Usb / Disks (Ncdu) - Анализ диска (или можно udiskie)
bind = $mainMod, U, exec, $scripts/open_overlay_tile.sh "kitty --class ncdu ncdu"
# E: Explorer (LF)
bind = $mainMod, P, exec, $scripts/open_overlay_tile.sh "kitty --class lf-overlay lf"
