# =============== Настройки раскладки тайлов =================
general {
    layout = master
}
master {
    orientation = left       # Стопка слева
    mfact = 0.50             # 50% экрана левому слоту
    new_status = slave       # Новое окно всегда летит в правую кучу
    new_on_top = true        # И сразу становится активным
}
misc {
    # ЗАПРЕЩАЕМ Hyprland закрывать оверлей, если мы убили в нем последнее окно.
    # Теперь он закроется ТОЛЬКО если мы явно попросим (через скрипт закрытия или toggle).
    close_special_on_empty = false
}

# ========================= Оверлей ==========================
# 1. Задаем поведение для workspace "special:overlay"
windowrulev2 = float, workspace:name:special:overlay
windowrulev2 = center, workspace:name:special:overlay
windowrulev2 = size 75% 70%, workspace:name:special:overlay
layerrule = dimaround, special:overlay
# === ЖЕСТКАЯ ПРИВЯЗКА КАПРИЗНЫХ ПРИЛОЖЕНИЙ ===
# Без этого они могут открываться на заднем плане или ломать скрипт
windowrulev2 = workspace special:overlay, class:^(pavucontrol)$
windowrulev2 = workspace special:overlay, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = workspace special:overlay, class:^(blueman-manager)$
windowrulev2 = workspace special:overlay, class:^(nm-connection-editor)$
# На всякий случай для Network Manager, иногда класс другой
windowrulev2 = workspace special:overlay, class:^(nm-applet)$ 
windowrulev2 = workspace special:overlay, class:^(nm-connection-editor)$

# Для Yazi и Btop тоже оставим, хуже не будет
windowrulev2 = workspace special:overlay, class:^(btop)$
windowrulev2 = workspace special:overlay, class:^(yazi-overlay)$
windowrulev2 = workspace special:overlay, class:^(ncdu)$
